# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repwgt',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('control', models.BigIntegerField(db_column=b'CONTROL', db_index=True)),
                ('repwgt0', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT0')),
                ('repwgt1', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT1')),
                ('repwgt10', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT10')),
                ('repwgt100', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT100')),
                ('repwgt101', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT101')),
                ('repwgt102', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT102')),
                ('repwgt103', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT103')),
                ('repwgt104', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT104')),
                ('repwgt105', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT105')),
                ('repwgt106', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT106')),
                ('repwgt107', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT107')),
                ('repwgt108', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT108')),
                ('repwgt109', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT109')),
                ('repwgt11', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT11')),
                ('repwgt110', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT110')),
                ('repwgt111', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT111')),
                ('repwgt112', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT112')),
                ('repwgt113', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT113')),
                ('repwgt114', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT114')),
                ('repwgt115', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT115')),
                ('repwgt116', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT116')),
                ('repwgt117', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT117')),
                ('repwgt118', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT118')),
                ('repwgt119', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT119')),
                ('repwgt12', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT12')),
                ('repwgt120', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT120')),
                ('repwgt121', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT121')),
                ('repwgt122', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT122')),
                ('repwgt123', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT123')),
                ('repwgt124', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT124')),
                ('repwgt125', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT125')),
                ('repwgt126', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT126')),
                ('repwgt127', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT127')),
                ('repwgt128', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT128')),
                ('repwgt129', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT129')),
                ('repwgt13', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT13')),
                ('repwgt130', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT130')),
                ('repwgt131', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT131')),
                ('repwgt132', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT132')),
                ('repwgt133', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT133')),
                ('repwgt134', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT134')),
                ('repwgt135', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT135')),
                ('repwgt136', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT136')),
                ('repwgt137', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT137')),
                ('repwgt138', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT138')),
                ('repwgt139', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT139')),
                ('repwgt14', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT14')),
                ('repwgt140', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT140')),
                ('repwgt141', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT141')),
                ('repwgt142', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT142')),
                ('repwgt143', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT143')),
                ('repwgt144', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT144')),
                ('repwgt145', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT145')),
                ('repwgt146', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT146')),
                ('repwgt147', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT147')),
                ('repwgt148', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT148')),
                ('repwgt149', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT149')),
                ('repwgt15', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT15')),
                ('repwgt150', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT150')),
                ('repwgt151', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT151')),
                ('repwgt152', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT152')),
                ('repwgt153', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT153')),
                ('repwgt154', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT154')),
                ('repwgt155', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT155')),
                ('repwgt156', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT156')),
                ('repwgt157', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT157')),
                ('repwgt158', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT158')),
                ('repwgt159', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT159')),
                ('repwgt16', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT16')),
                ('repwgt160', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT160')),
                ('repwgt17', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT17')),
                ('repwgt18', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT18')),
                ('repwgt19', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT19')),
                ('repwgt2', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT2')),
                ('repwgt20', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT20')),
                ('repwgt21', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT21')),
                ('repwgt22', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT22')),
                ('repwgt23', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT23')),
                ('repwgt24', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT24')),
                ('repwgt25', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT25')),
                ('repwgt26', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT26')),
                ('repwgt27', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT27')),
                ('repwgt28', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT28')),
                ('repwgt29', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT29')),
                ('repwgt3', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT3')),
                ('repwgt30', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT30')),
                ('repwgt31', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT31')),
                ('repwgt32', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT32')),
                ('repwgt33', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT33')),
                ('repwgt34', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT34')),
                ('repwgt35', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT35')),
                ('repwgt36', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT36')),
                ('repwgt37', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT37')),
                ('repwgt38', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT38')),
                ('repwgt39', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT39')),
                ('repwgt4', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT4')),
                ('repwgt40', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT40')),
                ('repwgt41', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT41')),
                ('repwgt42', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT42')),
                ('repwgt43', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT43')),
                ('repwgt44', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT44')),
                ('repwgt45', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT45')),
                ('repwgt46', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT46')),
                ('repwgt47', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT47')),
                ('repwgt48', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT48')),
                ('repwgt49', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT49')),
                ('repwgt5', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT5')),
                ('repwgt50', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT50')),
                ('repwgt51', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT51')),
                ('repwgt52', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT52')),
                ('repwgt53', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT53')),
                ('repwgt54', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT54')),
                ('repwgt55', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT55')),
                ('repwgt56', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT56')),
                ('repwgt57', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT57')),
                ('repwgt58', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT58')),
                ('repwgt59', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT59')),
                ('repwgt6', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT6')),
                ('repwgt60', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT60')),
                ('repwgt61', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT61')),
                ('repwgt62', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT62')),
                ('repwgt63', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT63')),
                ('repwgt64', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT64')),
                ('repwgt65', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT65')),
                ('repwgt66', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT66')),
                ('repwgt67', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT67')),
                ('repwgt68', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT68')),
                ('repwgt69', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT69')),
                ('repwgt7', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT7')),
                ('repwgt70', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT70')),
                ('repwgt71', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT71')),
                ('repwgt72', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT72')),
                ('repwgt73', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT73')),
                ('repwgt74', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT74')),
                ('repwgt75', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT75')),
                ('repwgt76', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT76')),
                ('repwgt77', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT77')),
                ('repwgt78', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT78')),
                ('repwgt79', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT79')),
                ('repwgt8', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT8')),
                ('repwgt80', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT80')),
                ('repwgt81', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT81')),
                ('repwgt82', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT82')),
                ('repwgt83', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT83')),
                ('repwgt84', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT84')),
                ('repwgt85', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT85')),
                ('repwgt86', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT86')),
                ('repwgt87', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT87')),
                ('repwgt88', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT88')),
                ('repwgt89', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT89')),
                ('repwgt9', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT9')),
                ('repwgt90', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT90')),
                ('repwgt91', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT91')),
                ('repwgt92', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT92')),
                ('repwgt93', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT93')),
                ('repwgt94', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT94')),
                ('repwgt95', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT95')),
                ('repwgt96', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT96')),
                ('repwgt97', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT97')),
                ('repwgt98', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT98')),
                ('repwgt99', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'REPWGT99')),
                ('splt1wgt0', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT0')),
                ('splt1wgt1', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT1')),
                ('splt1wgt10', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT10')),
                ('splt1wgt100', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT100')),
                ('splt1wgt101', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT101')),
                ('splt1wgt102', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT102')),
                ('splt1wgt103', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT103')),
                ('splt1wgt104', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT104')),
                ('splt1wgt105', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT105')),
                ('splt1wgt106', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT106')),
                ('splt1wgt107', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT107')),
                ('splt1wgt108', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT108')),
                ('splt1wgt109', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT109')),
                ('splt1wgt11', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT11')),
                ('splt1wgt110', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT110')),
                ('splt1wgt111', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT111')),
                ('splt1wgt112', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT112')),
                ('splt1wgt113', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT113')),
                ('splt1wgt114', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT114')),
                ('splt1wgt115', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT115')),
                ('splt1wgt116', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT116')),
                ('splt1wgt117', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT117')),
                ('splt1wgt118', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT118')),
                ('splt1wgt119', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT119')),
                ('splt1wgt12', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT12')),
                ('splt1wgt120', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT120')),
                ('splt1wgt121', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT121')),
                ('splt1wgt122', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT122')),
                ('splt1wgt123', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT123')),
                ('splt1wgt124', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT124')),
                ('splt1wgt125', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT125')),
                ('splt1wgt126', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT126')),
                ('splt1wgt127', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT127')),
                ('splt1wgt128', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT128')),
                ('splt1wgt129', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT129')),
                ('splt1wgt13', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT13')),
                ('splt1wgt130', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT130')),
                ('splt1wgt131', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT131')),
                ('splt1wgt132', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT132')),
                ('splt1wgt133', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT133')),
                ('splt1wgt134', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT134')),
                ('splt1wgt135', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT135')),
                ('splt1wgt136', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT136')),
                ('splt1wgt137', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT137')),
                ('splt1wgt138', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT138')),
                ('splt1wgt139', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT139')),
                ('splt1wgt14', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT14')),
                ('splt1wgt140', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT140')),
                ('splt1wgt141', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT141')),
                ('splt1wgt142', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT142')),
                ('splt1wgt143', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT143')),
                ('splt1wgt144', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT144')),
                ('splt1wgt145', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT145')),
                ('splt1wgt146', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT146')),
                ('splt1wgt147', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT147')),
                ('splt1wgt148', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT148')),
                ('splt1wgt149', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT149')),
                ('splt1wgt15', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT15')),
                ('splt1wgt150', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT150')),
                ('splt1wgt151', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT151')),
                ('splt1wgt152', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT152')),
                ('splt1wgt153', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT153')),
                ('splt1wgt154', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT154')),
                ('splt1wgt155', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT155')),
                ('splt1wgt156', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT156')),
                ('splt1wgt157', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT157')),
                ('splt1wgt158', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT158')),
                ('splt1wgt159', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT159')),
                ('splt1wgt16', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT16')),
                ('splt1wgt160', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT160')),
                ('splt1wgt17', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT17')),
                ('splt1wgt18', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT18')),
                ('splt1wgt19', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT19')),
                ('splt1wgt2', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT2')),
                ('splt1wgt20', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT20')),
                ('splt1wgt21', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT21')),
                ('splt1wgt22', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT22')),
                ('splt1wgt23', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT23')),
                ('splt1wgt24', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT24')),
                ('splt1wgt25', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT25')),
                ('splt1wgt26', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT26')),
                ('splt1wgt27', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT27')),
                ('splt1wgt28', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT28')),
                ('splt1wgt29', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT29')),
                ('splt1wgt3', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT3')),
                ('splt1wgt30', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT30')),
                ('splt1wgt31', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT31')),
                ('splt1wgt32', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT32')),
                ('splt1wgt33', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT33')),
                ('splt1wgt34', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT34')),
                ('splt1wgt35', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT35')),
                ('splt1wgt36', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT36')),
                ('splt1wgt37', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT37')),
                ('splt1wgt38', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT38')),
                ('splt1wgt39', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT39')),
                ('splt1wgt4', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT4')),
                ('splt1wgt40', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT40')),
                ('splt1wgt41', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT41')),
                ('splt1wgt42', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT42')),
                ('splt1wgt43', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT43')),
                ('splt1wgt44', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT44')),
                ('splt1wgt45', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT45')),
                ('splt1wgt46', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT46')),
                ('splt1wgt47', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT47')),
                ('splt1wgt48', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT48')),
                ('splt1wgt49', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT49')),
                ('splt1wgt5', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT5')),
                ('splt1wgt50', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT50')),
                ('splt1wgt51', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT51')),
                ('splt1wgt52', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT52')),
                ('splt1wgt53', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT53')),
                ('splt1wgt54', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT54')),
                ('splt1wgt55', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT55')),
                ('splt1wgt56', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT56')),
                ('splt1wgt57', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT57')),
                ('splt1wgt58', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT58')),
                ('splt1wgt59', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT59')),
                ('splt1wgt6', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT6')),
                ('splt1wgt60', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT60')),
                ('splt1wgt61', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT61')),
                ('splt1wgt62', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT62')),
                ('splt1wgt63', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT63')),
                ('splt1wgt64', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT64')),
                ('splt1wgt65', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT65')),
                ('splt1wgt66', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT66')),
                ('splt1wgt67', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT67')),
                ('splt1wgt68', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT68')),
                ('splt1wgt69', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT69')),
                ('splt1wgt7', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT7')),
                ('splt1wgt70', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT70')),
                ('splt1wgt71', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT71')),
                ('splt1wgt72', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT72')),
                ('splt1wgt73', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT73')),
                ('splt1wgt74', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT74')),
                ('splt1wgt75', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT75')),
                ('splt1wgt76', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT76')),
                ('splt1wgt77', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT77')),
                ('splt1wgt78', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT78')),
                ('splt1wgt79', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT79')),
                ('splt1wgt8', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT8')),
                ('splt1wgt80', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT80')),
                ('splt1wgt81', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT81')),
                ('splt1wgt82', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT82')),
                ('splt1wgt83', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT83')),
                ('splt1wgt84', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT84')),
                ('splt1wgt85', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT85')),
                ('splt1wgt86', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT86')),
                ('splt1wgt87', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT87')),
                ('splt1wgt88', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT88')),
                ('splt1wgt89', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT89')),
                ('splt1wgt9', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT9')),
                ('splt1wgt90', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT90')),
                ('splt1wgt91', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT91')),
                ('splt1wgt92', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT92')),
                ('splt1wgt93', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT93')),
                ('splt1wgt94', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT94')),
                ('splt1wgt95', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT95')),
                ('splt1wgt96', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT96')),
                ('splt1wgt97', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT97')),
                ('splt1wgt98', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT98')),
                ('splt1wgt99', models.PositiveIntegerField(null=True, db_column=b'SPLT1WGT99')),
                ('splt2wgt0', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT0')),
                ('splt2wgt1', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT1')),
                ('splt2wgt10', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT10')),
                ('splt2wgt100', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT100')),
                ('splt2wgt101', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT101')),
                ('splt2wgt102', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT102')),
                ('splt2wgt103', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT103')),
                ('splt2wgt104', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT104')),
                ('splt2wgt105', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT105')),
                ('splt2wgt106', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT106')),
                ('splt2wgt107', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT107')),
                ('splt2wgt108', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT108')),
                ('splt2wgt109', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT109')),
                ('splt2wgt11', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT11')),
                ('splt2wgt110', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT110')),
                ('splt2wgt111', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT111')),
                ('splt2wgt112', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT112')),
                ('splt2wgt113', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT113')),
                ('splt2wgt114', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT114')),
                ('splt2wgt115', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT115')),
                ('splt2wgt116', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT116')),
                ('splt2wgt117', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT117')),
                ('splt2wgt118', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT118')),
                ('splt2wgt119', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT119')),
                ('splt2wgt12', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT12')),
                ('splt2wgt120', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT120')),
                ('splt2wgt121', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT121')),
                ('splt2wgt122', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT122')),
                ('splt2wgt123', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT123')),
                ('splt2wgt124', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT124')),
                ('splt2wgt125', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT125')),
                ('splt2wgt126', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT126')),
                ('splt2wgt127', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT127')),
                ('splt2wgt128', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT128')),
                ('splt2wgt129', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT129')),
                ('splt2wgt13', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT13')),
                ('splt2wgt130', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT130')),
                ('splt2wgt131', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT131')),
                ('splt2wgt132', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT132')),
                ('splt2wgt133', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT133')),
                ('splt2wgt134', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT134')),
                ('splt2wgt135', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT135')),
                ('splt2wgt136', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT136')),
                ('splt2wgt137', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT137')),
                ('splt2wgt138', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT138')),
                ('splt2wgt139', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT139')),
                ('splt2wgt14', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT14')),
                ('splt2wgt140', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT140')),
                ('splt2wgt141', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT141')),
                ('splt2wgt142', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT142')),
                ('splt2wgt143', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT143')),
                ('splt2wgt144', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT144')),
                ('splt2wgt145', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT145')),
                ('splt2wgt146', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT146')),
                ('splt2wgt147', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT147')),
                ('splt2wgt148', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT148')),
                ('splt2wgt149', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT149')),
                ('splt2wgt15', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT15')),
                ('splt2wgt150', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT150')),
                ('splt2wgt151', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT151')),
                ('splt2wgt152', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT152')),
                ('splt2wgt153', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT153')),
                ('splt2wgt154', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT154')),
                ('splt2wgt155', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT155')),
                ('splt2wgt156', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT156')),
                ('splt2wgt157', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT157')),
                ('splt2wgt158', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT158')),
                ('splt2wgt159', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT159')),
                ('splt2wgt16', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT16')),
                ('splt2wgt160', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT160')),
                ('splt2wgt17', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT17')),
                ('splt2wgt18', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT18')),
                ('splt2wgt19', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT19')),
                ('splt2wgt2', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT2')),
                ('splt2wgt20', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT20')),
                ('splt2wgt21', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT21')),
                ('splt2wgt22', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT22')),
                ('splt2wgt23', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT23')),
                ('splt2wgt24', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT24')),
                ('splt2wgt25', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT25')),
                ('splt2wgt26', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT26')),
                ('splt2wgt27', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT27')),
                ('splt2wgt28', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT28')),
                ('splt2wgt29', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT29')),
                ('splt2wgt3', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT3')),
                ('splt2wgt30', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT30')),
                ('splt2wgt31', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT31')),
                ('splt2wgt32', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT32')),
                ('splt2wgt33', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT33')),
                ('splt2wgt34', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT34')),
                ('splt2wgt35', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT35')),
                ('splt2wgt36', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT36')),
                ('splt2wgt37', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT37')),
                ('splt2wgt38', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT38')),
                ('splt2wgt39', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT39')),
                ('splt2wgt4', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT4')),
                ('splt2wgt40', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT40')),
                ('splt2wgt41', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT41')),
                ('splt2wgt42', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT42')),
                ('splt2wgt43', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT43')),
                ('splt2wgt44', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT44')),
                ('splt2wgt45', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT45')),
                ('splt2wgt46', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT46')),
                ('splt2wgt47', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT47')),
                ('splt2wgt48', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT48')),
                ('splt2wgt49', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT49')),
                ('splt2wgt5', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT5')),
                ('splt2wgt50', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT50')),
                ('splt2wgt51', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT51')),
                ('splt2wgt52', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT52')),
                ('splt2wgt53', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT53')),
                ('splt2wgt54', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT54')),
                ('splt2wgt55', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT55')),
                ('splt2wgt56', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT56')),
                ('splt2wgt57', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT57')),
                ('splt2wgt58', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT58')),
                ('splt2wgt59', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT59')),
                ('splt2wgt6', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT6')),
                ('splt2wgt60', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT60')),
                ('splt2wgt61', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT61')),
                ('splt2wgt62', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT62')),
                ('splt2wgt63', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT63')),
                ('splt2wgt64', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT64')),
                ('splt2wgt65', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT65')),
                ('splt2wgt66', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT66')),
                ('splt2wgt67', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT67')),
                ('splt2wgt68', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT68')),
                ('splt2wgt69', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT69')),
                ('splt2wgt7', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT7')),
                ('splt2wgt70', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT70')),
                ('splt2wgt71', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT71')),
                ('splt2wgt72', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT72')),
                ('splt2wgt73', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT73')),
                ('splt2wgt74', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT74')),
                ('splt2wgt75', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT75')),
                ('splt2wgt76', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT76')),
                ('splt2wgt77', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT77')),
                ('splt2wgt78', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT78')),
                ('splt2wgt79', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT79')),
                ('splt2wgt8', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT8')),
                ('splt2wgt80', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT80')),
                ('splt2wgt81', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT81')),
                ('splt2wgt82', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT82')),
                ('splt2wgt83', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT83')),
                ('splt2wgt84', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT84')),
                ('splt2wgt85', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT85')),
                ('splt2wgt86', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT86')),
                ('splt2wgt87', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT87')),
                ('splt2wgt88', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT88')),
                ('splt2wgt89', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT89')),
                ('splt2wgt9', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT9')),
                ('splt2wgt90', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT90')),
                ('splt2wgt91', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT91')),
                ('splt2wgt92', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT92')),
                ('splt2wgt93', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT93')),
                ('splt2wgt94', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT94')),
                ('splt2wgt95', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT95')),
                ('splt2wgt96', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT96')),
                ('splt2wgt97', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT97')),
                ('splt2wgt98', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT98')),
                ('splt2wgt99', models.PositiveIntegerField(null=True, db_column=b'SPLT2WGT99')),
                ('export_year', models.PositiveSmallIntegerField(null=True, db_index=True)),
            ],
            options={
                'db_table': 'ahs_repwgt',
            },
        ),
        migrations.AlterIndexTogether(
            name='repwgt',
            index_together=set([('control', 'export_year')]),
        ),
    ]
