from django.db import models


class Person(models.Model):
    class Meta:
        db_table = 'ahs_person'
        index_together = [
            ['control', 'pline'],
            ['control', 'export_year']
        ]

    control = models.BigIntegerField(db_column='CONTROL', db_index=True, null=False)

    age = models.PositiveSmallIntegerField(db_column='AGE', null=True)
    citshp = models.PositiveSmallIntegerField(db_column='CITSHP', null=True)
    famnum = models.PositiveSmallIntegerField(db_column='FAMNUM', null=True)
    famrel = models.PositiveSmallIntegerField(db_column='FAMREL', null=True)
    famtyp = models.PositiveSmallIntegerField(db_column='FAMTYP', null=True)
    food = models.SmallIntegerField(db_column='FOOD', null=True)
    grad = models.SmallIntegerField(db_column='GRAD', null=True)
    here = models.SmallIntegerField(db_column='HERE', null=True)
    inusyr = models.IntegerField(db_column='INUSYR', null=True)
    jage = models.SmallIntegerField(db_column='JAGE', null=True)
    jatvty = models.SmallIntegerField(db_column='JATVTY', null=True)
    jgrad = models.SmallIntegerField(db_column='JGRAD', null=True)
    jhere = models.SmallIntegerField(db_column='jhere', null=True)
    jitshp = models.SmallIntegerField(db_column='JITSHP', null=True)
    jmar = models.SmallIntegerField(db_column='JMAR', null=True)
    jmove = models.SmallIntegerField(db_column='JMOVE', null=True)
    jmovm = models.SmallIntegerField(db_column='JMOVM', null=True)
    jmvg = models.SmallIntegerField(db_column='JMVG', null=True)
    jnusyr = models.SmallIntegerField(db_column='JNUSYR', null=True)
    jpar = models.SmallIntegerField(db_column='JPAR', null=True)
    jpqalim = models.SmallIntegerField(db_column='JPQALIM', null=True)
    jpqdiv = models.SmallIntegerField(db_column='JPQDIV', null=True)
    jpqidri = models.SmallIntegerField(db_column='JPQIDRI', null=True)
    jpqint = models.SmallIntegerField(db_column='JPQINT', null=True)
    jpqotalm = models.SmallIntegerField(db_column='JPQOTALM', null=True)
    jpqother = models.SmallIntegerField(db_column='JPQOTHER', null=True)
    jpqothnr = models.SmallIntegerField(db_column='JPQOTHNR', null=True)
    jpqrent = models.SmallIntegerField(db_column='JPQRENT', null=True)
    jpqretir = models.SmallIntegerField(db_column='JPQRETIR', null=True)
    jpqsal = models.SmallIntegerField(db_column='JPQSAL', null=True)
    jpqsalnr = models.SmallIntegerField(db_column='JPQSALNR', null=True)
    jpqself = models.SmallIntegerField(db_column='JPQSELF', null=True)
    jpqslfnr = models.SmallIntegerField(db_column='JPQSLFNR', null=True)
    jpqss = models.SmallIntegerField(db_column='JPQSS', null=True)
    jpqssi = models.SmallIntegerField(db_column='JPQSSI', null=True)
    jpqwelf = models.SmallIntegerField(db_column='JPQWELF', null=True)
    jpqwkcmp = models.SmallIntegerField(db_column='JPQWKCMP', null=True)
    jpvother = models.SmallIntegerField(db_column='JPVOTHER', null=True)
    jrace = models.SmallIntegerField(db_column='JRACE', null=True)
    jrel = models.SmallIntegerField(db_column='JREL', null=True)
    jsal = models.SmallIntegerField(db_column='JSAL', null=True)
    jsex = models.SmallIntegerField(db_column='JSEX', null=True)
    jspan = models.SmallIntegerField(db_column='JSPAN', null=True)
    jspos = models.SmallIntegerField(db_column='JSPOS', null=True)
    jten = models.SmallIntegerField(db_column='JTEN', null=True)
    lodrnt = models.IntegerField(db_column='LODRNT', null=True)
    lodsta = models.SmallIntegerField(db_column='LODSTA', null=True)
    mar = models.SmallIntegerField(db_column='MAR', null=True)
    move = models.PositiveIntegerField(db_column='MOVE', null=True)
    movm = models.PositiveSmallIntegerField(db_column='MOVM', null=True)
    mvg = models.SmallIntegerField(db_column='MVG', null=True)
    natvty = models.PositiveIntegerField(db_column='NATVTY', null=True)
    othest = models.SmallIntegerField(db_column='OTHEST', null=True)
    par = models.SmallIntegerField(db_column='PAR', null=True)
    pasthwho = models.SmallIntegerField(db_column='PASTHWHO', null=True)
    pbtub = models.SmallIntegerField(db_column='PBTUB', null=True)
    pcare = models.SmallIntegerField(db_column='PCARE', null=True)
    pctruse = models.SmallIntegerField(db_column='PCTRUSE', null=True)
    perrnd = models.SmallIntegerField(db_column='PERRND', null=True)
    person = models.PositiveSmallIntegerField(db_column='PERSON', null=True)
    pfaucet = models.SmallIntegerField(db_column='PFAUCET', null=True)
    pgetbr = models.SmallIntegerField(db_column='PGETBR', null=True)
    pgrasp = models.SmallIntegerField(db_column='PGRASP', null=True)
    phear = models.SmallIntegerField(db_column='PHEAR', null=True)
    pkcab = models.SmallIntegerField(db_column='PKCAB', null=True)
    pline = models.PositiveSmallIntegerField(db_column='PLINE', null=True)
    pmemry = models.SmallIntegerField(db_column='PMEMRY', null=True)
    pocab = models.SmallIntegerField(db_column='POCAB', null=True)
    pqalim = models.SmallIntegerField(db_column='PQALIM', null=True)
    pqdiv = models.SmallIntegerField(db_column='PQDIV', null=True)
    pqidri = models.SmallIntegerField(db_column='PQIDRI', null=True)
    pqint = models.SmallIntegerField(db_column='PQINT', null=True)
    pqotalm = models.SmallIntegerField(db_column='PQOTALM', null=True)
    pqother = models.SmallIntegerField(db_column='PQOTHER', null=True)
    pqothnr = models.SmallIntegerField(db_column='PQOTHNR', null=True)
    pqrent = models.SmallIntegerField(db_column='PQRENT', null=True)
    pqretir = models.SmallIntegerField(db_column='PQRETIR', null=True)
    pqsal = models.SmallIntegerField(db_column='PQSAL', null=True)
    pqsalnr = models.SmallIntegerField(db_column='PQSALNR', null=True)
    pqself = models.SmallIntegerField(db_column='PQSELF', null=True)
    pqselfnr = models.SmallIntegerField(db_column='PQSELFNR', null=True)
    pqss = models.SmallIntegerField(db_column='PQSS', null=True)
    pqssi = models.SmallIntegerField(db_column='PQSSI', null=True)
    pqwelf = models.SmallIntegerField(db_column='PQWELF', null=True)
    pqwkcmp = models.SmallIntegerField(db_column='PQWKCMP', null=True)
    preach = models.SmallIntegerField(db_column='PREACH', null=True)
    psee = models.SmallIntegerField(db_column='PSEE', null=True)
    psink = models.SmallIntegerField(db_column='PSINK', null=True)
    pstoop = models.SmallIntegerField(db_column='PSTOOP', null=True)
    pstov = models.SmallIntegerField(db_column='PSTOV', null=True)
    pvother = models.IntegerField(db_column='PVOTHER', null=True)
    pwalk = models.SmallIntegerField(db_column='PWALK', null=True)
    pwshwr = models.SmallIntegerField(db_column='PWSHWR', null=True)
    race = models.PositiveSmallIntegerField(db_column='RACE', null=True)
    rel = models.PositiveSmallIntegerField(db_column='REL', null=True)
    rntdue = models.SmallIntegerField(db_column='RNTDUE', null=True)
    sal = models.IntegerField(db_column='SAL', null=True)
    sex = models.PositiveSmallIntegerField(db_column='SEX', null=True)
    span = models.PositiveSmallIntegerField(db_column='SPAN', null=True)
    spos = models.SmallIntegerField(db_column='SPOS', null=True)
    ten = models.SmallIntegerField(db_column='TEN', null=True)
    wlineq = models.SmallIntegerField(db_column='WLINEQ', null=True)

    export_year = models.PositiveSmallIntegerField(null=True, db_index=True)
