from django.db import models


class Topical(models.Model):
    class Meta:
        db_table = 'ahs_topical'
        index_together = [
            ['control', 'export_year'],
            ['field_in_2013', 'field_in_2011']
        ]

    control = models.BigIntegerField(db_column='CONTROL', unique=True, primary_key=True)

    cefclosknit = models.SmallIntegerField(db_column='CEFCLOSKNIT', null=True)
    cefdisrspct = models.SmallIntegerField(db_column='CEFDISRSPCT', null=True)
    ceffighting = models.SmallIntegerField(db_column='CEFFIGHTING', null=True)
    ceffiresta = models.SmallIntegerField(db_column='CEFFIRESTA', null=True)
    cefgetalong = models.SmallIntegerField(db_column='CEFGETALONG', null=True)
    cefgpblock = models.SmallIntegerField(db_column='CEFGPBLOCK', null=True)
    cefgpchurch = models.SmallIntegerField(db_column='CEFGPCHURCH', null=True)
    cefgpcivic = models.SmallIntegerField(db_column='CEFGPCIVIC', null=True)
    cefhelpnbor = models.SmallIntegerField(db_column='CEFHELPNBOR', null=True)
    cefsharvals = models.SmallIntegerField(db_column='CEFSHARVALS', null=True)
    cefskipschl = models.SmallIntegerField(db_column='CEFSKIPSCHL', null=True)
    cefspkmeetg = models.SmallIntegerField(db_column='CEFSPKMEETG', null=True)
    cefspknbors = models.SmallIntegerField(db_column='CEFSPKNBORS', null=True)
    cefspkoffcl = models.SmallIntegerField(db_column='CEFSPKOFFCL', null=True)
    cefspkprblm = models.SmallIntegerField(db_column='CEFSPKPRBLM', null=True)
    cefspkrelg = models.SmallIntegerField(db_column='CEFSPKRELG', null=True)
    cefsprypnt = models.SmallIntegerField(db_column='CEFSPRYPNT', null=True)
    ceftrusted = models.SmallIntegerField(db_column='CEFTRUSTED', null=True)
    dpaltcom = models.SmallIntegerField(db_column='DPALTCOM', null=True)
    dpbnread = models.SmallIntegerField(db_column='DPBNREAD', null=True)
    dpdrfood = models.SmallIntegerField(db_column='DPDRFOOD', null=True)
    dpemwater = models.SmallIntegerField(db_column='DPEMWATER', null=True)
    dpevacpets = models.SmallIntegerField(db_column='DPEVACPETS', null=True)
    dpevfin = models.SmallIntegerField(db_column='DPEVFIN', null=True)
    dpevinfo = models.SmallIntegerField(db_column='DPEVINFO', null=True)
    dpevkit = models.SmallIntegerField(db_column='DPEVKIT', null=True)
    dpevloc = models.SmallIntegerField(db_column='DPEVLOC', null=True)
    dpevsep = models.SmallIntegerField(db_column='DPEVSEP', null=True)
    dpevvehic = models.SmallIntegerField(db_column='DPEVVEHIC', null=True)
    dpgenert = models.SmallIntegerField(db_column='DPGENERT', null=True)
    drugstore = models.SmallIntegerField(db_column='DRUGSTORE', null=True)
    eaban = models.SmallIntegerField(db_column='EABAN', null=True)
    eage = models.SmallIntegerField(db_column='EAGE', null=True)
    ebarcl = models.SmallIntegerField(db_column='EBARCL', null=True)
    ecom1 = models.SmallIntegerField(db_column='ECOM1', null=True)
    ecom2 = models.SmallIntegerField(db_column='ECOM2', null=True)
    egreen = models.SmallIntegerField(db_column='EGREEN', null=True)
    eheight = models.SmallIntegerField(db_column='EHEIGHT', null=True)
    ejunk = models.SmallIntegerField(db_column='EJUNK', null=True)
    eprkg = models.SmallIntegerField(db_column='EPRKG', null=True)
    eroad = models.SmallIntegerField(db_column='EROAD', null=True)
    etrans = models.SmallIntegerField(db_column='ETRANS', null=True)
    ewater = models.SmallIntegerField(db_column='EWATER', null=True)
    friends = models.SmallIntegerField(db_column='FRIENDS', null=True)
    grocery = models.SmallIntegerField(db_column='GROCERY', null=True)
    nhdbldmh = models.SmallIntegerField(db_column='NHDBLDMH', null=True)
    nhdbldmu = models.SmallIntegerField(db_column='NHDBLDMU', null=True)
    nhdbldsua = models.SmallIntegerField(db_column='NHDBLDSUA', null=True)
    nhdbldsud = models.SmallIntegerField(db_column='NHDBLDSUD', null=True)
    ptbank = models.SmallIntegerField(db_column='PTBANK', null=True)
    ptcostcarm = models.IntegerField(db_column='PTCOSTCARM', null=True)
    ptcostcarp = models.IntegerField(db_column='PTCOSTCARP', null=True)
    ptcostgas = models.IntegerField(db_column='PTCOSTGAS', null=True)
    ptcostinsu = models.IntegerField(db_column='PTCOSTINSU', null=True)
    ptcostpark = models.IntegerField(db_column='PTCOSTPARK', null=True)
    ptcostptr = models.IntegerField(db_column='PTCOSTPTR', null=True)
    ptdisbus = models.SmallIntegerField(db_column='PTDISBUS', null=True)
    ptdispub = models.SmallIntegerField(db_column='PTDISPUB', null=True)
    ptdisrail = models.SmallIntegerField(db_column='PTDISRAIL', null=True)
    ptdisshut = models.SmallIntegerField(db_column='PTDISSHUT', null=True)
    ptdissub = models.SmallIntegerField(db_column='PTDISSUB', null=True)
    ptentmnt = models.SmallIntegerField(db_column='PTENTMNT', null=True)
    ptgetbus = models.SmallIntegerField(db_column='PTGETBUS', null=True)
    ptgetrail = models.SmallIntegerField(db_column='PTGETRAIL', null=True)
    ptgetshut = models.SmallIntegerField(db_column='PTGETSHUT', null=True)
    ptgetsub = models.SmallIntegerField(db_column='PTGETSUB', null=True)
    ptgrocer = models.SmallIntegerField(db_column='PTGROCER', null=True)
    pthealth = models.SmallIntegerField(db_column='PTHEALTH', null=True)
    ptoftbus = models.SmallIntegerField(db_column='PTOFTBUS', null=True)
    ptoftrail = models.SmallIntegerField(db_column='PTOFTRAIL', null=True)
    ptoftshut = models.SmallIntegerField(db_column='PTOFTSHUT', null=True)
    ptoftsub = models.SmallIntegerField(db_column='PTOFTSUB', null=True)
    ptpubtrn = models.SmallIntegerField(db_column='PTPUBTRN', null=True)
    ptretail = models.SmallIntegerField(db_column='PTRETAIL', null=True)
    ptservic = models.SmallIntegerField(db_column='PTSERVIC', null=True)
    ptusbus = models.SmallIntegerField(db_column='PTUSBUS', null=True)
    ptuscrpl = models.SmallIntegerField(db_column='PTUSCRPL', null=True)
    ptuscrsh = models.SmallIntegerField(db_column='PTUSCRSH', null=True)
    ptusotr = models.SmallIntegerField(db_column='PTUSOTR', null=True)
    ptusrail = models.SmallIntegerField(db_column='PTUSRAIL', null=True)
    ptusshut = models.SmallIntegerField(db_column='PTUSSHUT', null=True)
    ptussub = models.SmallIntegerField(db_column='PTUSSUB', null=True)
    ptustaxi = models.SmallIntegerField(db_column='PTUSTAXI', null=True)
    ptwkschl = models.SmallIntegerField(db_column='PTWKSCHL', null=True)
    satpol = models.SmallIntegerField(db_column='SATPOL', null=True)
    spltwgt1 = models.DecimalField(db_column='SPLTWGT1', max_digits=20, decimal_places=10, null=True)
    spltwgt2 = models.DecimalField(db_column='SPLTWGT2', max_digits=20, decimal_places=10, null=True)
    talknbor = models.SmallIntegerField(db_column='TALKNBOR', null=True)
    volnteer = models.SmallIntegerField(db_column='VOLNTEER', null=True)
    wbbank = models.SmallIntegerField(db_column='WBBANK', null=True)
    wbbikelane = models.SmallIntegerField(db_column='WBBIKELANE', null=True)
    wbbikewalk = models.SmallIntegerField(db_column='WBBIKEWALK', null=True)
    wbentmnt = models.SmallIntegerField(db_column='WBENTMNT', null=True)
    wbgrocer = models.SmallIntegerField(db_column='WBGROCER', null=True)
    wbhealth = models.SmallIntegerField(db_column='WBHEALTH', null=True)
    wbnobike = models.SmallIntegerField(db_column='WBNOBIKE', null=True)
    wbnobkbdsw = models.SmallIntegerField(db_column='WBNOBKBDSW', null=True)
    wbnobkbike = models.SmallIntegerField(db_column='WBNOBKBIKE', null=True)
    wbnobkcrim = models.SmallIntegerField(db_column='WBNOBKCRIM', null=True)
    wbnobkdest = models.SmallIntegerField(db_column='WBNOBKDEST', null=True)
    wbnobkfast = models.SmallIntegerField(db_column='WBNOBKFAST', null=True)
    wbnobkhlth = models.SmallIntegerField(db_column='WBNOBKHLTH', null=True)
    wbnobklane = models.SmallIntegerField(db_column='WBNOBKLANE', null=True)
    wbnobklite = models.SmallIntegerField(db_column='WBNOBKLITE', null=True)
    wbnobknosw = models.SmallIntegerField(db_column='WBNOBKNOSW', null=True)
    wbnobkothr = models.SmallIntegerField(db_column='WBNOBKOTHR', null=True)
    wbnobktime = models.SmallIntegerField(db_column='WBNOBKTIME', null=True)
    wbnobktraf = models.SmallIntegerField(db_column='WBNOBKTRAF', null=True)
    wbretail = models.SmallIntegerField(db_column='WBRETAIL', null=True)
    wbservic = models.SmallIntegerField(db_column='WBSERVIC', null=True)
    wbsidewalk = models.SmallIntegerField(db_column='WBSIDEWALK', null=True)
    wbwkschl = models.SmallIntegerField(db_column='WBWKSCHL', null=True)
    wfprop = models.SmallIntegerField(db_column='WFPROP', null=True)

    field_in_2013 = models.BooleanField(default=False)
    field_in_2011 = models.BooleanField(default=False)

    export_year = models.PositiveSmallIntegerField(null=True, db_index=True)
