# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('control', models.BigIntegerField(null=True, db_column=b'CONTROL', db_index=True)),
                ('pqint', models.SmallIntegerField(null=True, db_column=b'PQINT')),
                ('par', models.SmallIntegerField(null=True, db_column=b'PAR')),
                ('movm', models.PositiveSmallIntegerField(null=True, db_column=b'MOVM')),
                ('pqssi', models.SmallIntegerField(null=True, db_column=b'PQSSI')),
                ('pqss', models.SmallIntegerField(null=True, db_column=b'PQSS')),
                ('age', models.PositiveSmallIntegerField(null=True, db_column=b'AGE')),
                ('move', models.PositiveIntegerField(null=True, db_column=b'MOVE')),
                ('pqsalnr', models.SmallIntegerField(null=True, db_column=b'PQSALNR')),
                ('jpqrent', models.SmallIntegerField(null=True, db_column=b'JPQRENT')),
                ('pcare', models.SmallIntegerField(null=True, db_column=b'PCARE')),
                ('jpqslfnr', models.SmallIntegerField(null=True, db_column=b'JPQSLFNR')),
                ('pqother', models.SmallIntegerField(null=True, db_column=b'PQOTHER')),
                ('jpqother', models.SmallIntegerField(null=True, db_column=b'JPQOTHER')),
                ('jmovm', models.SmallIntegerField(null=True, db_column=b'JMOVM')),
                ('jpqself', models.SmallIntegerField(null=True, db_column=b'JPQSELF')),
                ('pmemry', models.SmallIntegerField(null=True, db_column=b'PMEMRY')),
                ('pqself', models.SmallIntegerField(null=True, db_column=b'PQSELF')),
                ('lodrnt', models.IntegerField(null=True, db_column=b'LODRNT')),
                ('jten', models.SmallIntegerField(null=True, db_column=b'JTEN')),
                ('jmove', models.SmallIntegerField(null=True, db_column=b'JMOVE')),
                ('phear', models.SmallIntegerField(null=True, db_column=b'PHEAR')),
                ('rel', models.PositiveSmallIntegerField(null=True, db_column=b'REL')),
                ('jsal', models.SmallIntegerField(null=True, db_column=b'JSAL')),
                ('ten', models.PositiveSmallIntegerField(null=True, db_column=b'TEN')),
                ('jspan', models.SmallIntegerField(null=True, db_column=b'JSPAN')),
                ('jspos', models.SmallIntegerField(null=True, db_column=b'JSPOS')),
                ('sal', models.IntegerField(null=True, db_column=b'SAL')),
                ('jrel', models.SmallIntegerField(null=True, db_column=b'JREL')),
                ('jmar', models.SmallIntegerField(null=True, db_column=b'JMAR')),
                ('sex', models.PositiveSmallIntegerField(null=True, db_column=b'SEX')),
                ('psee', models.SmallIntegerField(null=True, db_column=b'PSEE')),
                ('race', models.PositiveSmallIntegerField(null=True, db_column=b'RACE')),
                ('pqrent', models.SmallIntegerField(null=True, db_column=b'PQRENT')),
                ('pqretir', models.SmallIntegerField(null=True, db_column=b'PQRETIR')),
                ('pqsal', models.SmallIntegerField(null=True, db_column=b'PQSAL')),
                ('grad', models.SmallIntegerField(null=True, db_column=b'GRAD')),
                ('pqwkcmp', models.SmallIntegerField(null=True, db_column=b'PQWKCMP')),
                ('jpqsal', models.SmallIntegerField(null=True, db_column=b'JPQSAL')),
                ('jpqint', models.SmallIntegerField(null=True, db_column=b'JPQINT')),
                ('jpqothnr', models.SmallIntegerField(null=True, db_column=b'JPQOTHNR')),
                ('pline', models.PositiveSmallIntegerField(null=True, db_column=b'PLINE', db_index=True)),
                ('jrace', models.SmallIntegerField(null=True, db_column=b'JRACE')),
                ('jatvty', models.SmallIntegerField(null=True, db_column=b'JATVTY')),
                ('jpqwkcmp', models.SmallIntegerField(null=True, db_column=b'JPQWKCMP')),
                ('food', models.SmallIntegerField(null=True, db_column=b'FOOD')),
                ('perrnd', models.SmallIntegerField(null=True, db_column=b'PERRND')),
                ('jpvother', models.SmallIntegerField(null=True, db_column=b'JPVOTHER')),
                ('spos', models.SmallIntegerField(null=True, db_column=b'SPOS')),
                ('rntdue', models.SmallIntegerField(null=True, db_column=b'RNTDUE')),
                ('inusyr', models.IntegerField(null=True, db_column=b'INUSYR')),
                ('jage', models.SmallIntegerField(null=True, db_column=b'JAGE')),
                ('jpqssi', models.SmallIntegerField(null=True, db_column=b'JPQSSI')),
                ('pqalim', models.SmallIntegerField(null=True, db_column=b'PQALIM')),
                ('natvty', models.PositiveIntegerField(null=True, db_column=b'NATVTY')),
                ('pqselfnr', models.SmallIntegerField(null=True, db_column=b'PQSELFNR')),
                ('jpqretir', models.SmallIntegerField(null=True, db_column=b'JPQRETIR')),
                ('pqwelf', models.SmallIntegerField(null=True, db_column=b'PQWELF')),
                ('mvg', models.SmallIntegerField(null=True, db_column=b'MVG')),
                ('famrel', models.PositiveSmallIntegerField(null=True, db_column=b'FAMREL')),
                ('citshp', models.PositiveSmallIntegerField(null=True, db_column=b'CITSHP')),
                ('jpqalim', models.SmallIntegerField(null=True, db_column=b'JPQALIM')),
                ('jpar', models.SmallIntegerField(null=True, db_column=b'JPAR')),
                ('jgrad', models.SmallIntegerField(null=True, db_column=b'JGRAD')),
                ('pvother', models.IntegerField(null=True, db_column=b'PVOTHER')),
                ('famnum', models.PositiveSmallIntegerField(null=True, db_column=b'FAMNUM')),
                ('mar', models.SmallIntegerField(null=True, db_column=b'MAR')),
                ('span', models.PositiveSmallIntegerField(null=True, db_column=b'SPAN')),
                ('pqdiv', models.SmallIntegerField(null=True, db_column=b'PQDIV')),
                ('pwalk', models.SmallIntegerField(null=True, db_column=b'PWALK')),
                ('pqothnr', models.SmallIntegerField(null=True, db_column=b'PQOTHNR')),
                ('jpqdiv', models.SmallIntegerField(null=True, db_column=b'JPQDIV')),
                ('jitshp', models.SmallIntegerField(null=True, db_column=b'JITSHP')),
                ('jpqss', models.SmallIntegerField(null=True, db_column=b'JPQSS')),
                ('smsa', models.PositiveIntegerField(null=True, db_column=b'SMSA', db_index=True)),
                ('jnusyr', models.SmallIntegerField(null=True, db_column=b'JNUSYR')),
                ('person', models.PositiveSmallIntegerField(null=True, db_column=b'PERSON')),
                ('jpqsalnr', models.SmallIntegerField(null=True, db_column=b'JPQSALNR')),
                ('jmvg', models.SmallIntegerField(null=True, db_column=b'JMVG')),
                ('jsex', models.SmallIntegerField(null=True, db_column=b'JSEX')),
                ('jpqwelf', models.SmallIntegerField(null=True, db_column=b'JPQWELF')),
                ('lodsta', models.SmallIntegerField(null=True, db_column=b'LODSTA')),
                ('famtyp', models.PositiveSmallIntegerField(null=True, db_column=b'FAMTYP')),
            ],
            options={
                'db_table': 'ahs_person',
            },
        ),
        migrations.AlterIndexTogether(
            name='person',
            index_together=set([('control', 'pline')]),
        ),
    ]
