# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topical',
            fields=[
                ('control', models.BigIntegerField(unique=True, serialize=False, primary_key=True, db_column=b'CONTROL')),
                ('cefclosknit', models.SmallIntegerField(null=True, db_column=b'CEFCLOSKNIT')),
                ('cefdisrspct', models.SmallIntegerField(null=True, db_column=b'CEFDISRSPCT')),
                ('ceffighting', models.SmallIntegerField(null=True, db_column=b'CEFFIGHTING')),
                ('ceffiresta', models.SmallIntegerField(null=True, db_column=b'CEFFIRESTA')),
                ('cefgetalong', models.SmallIntegerField(null=True, db_column=b'CEFGETALONG')),
                ('cefgpblock', models.SmallIntegerField(null=True, db_column=b'CEFGPBLOCK')),
                ('cefgpchurch', models.SmallIntegerField(null=True, db_column=b'CEFGPCHURCH')),
                ('cefgpcivic', models.SmallIntegerField(null=True, db_column=b'CEFGPCIVIC')),
                ('cefhelpnbor', models.SmallIntegerField(null=True, db_column=b'CEFHELPNBOR')),
                ('cefsharvals', models.SmallIntegerField(null=True, db_column=b'CEFSHARVALS')),
                ('cefskipschl', models.SmallIntegerField(null=True, db_column=b'CEFSKIPSCHL')),
                ('cefspkmeetg', models.SmallIntegerField(null=True, db_column=b'CEFSPKMEETG')),
                ('cefspknbors', models.SmallIntegerField(null=True, db_column=b'CEFSPKNBORS')),
                ('cefspkoffcl', models.SmallIntegerField(null=True, db_column=b'CEFSPKOFFCL')),
                ('cefspkprblm', models.SmallIntegerField(null=True, db_column=b'CEFSPKPRBLM')),
                ('cefspkrelg', models.SmallIntegerField(null=True, db_column=b'CEFSPKRELG')),
                ('cefsprypnt', models.SmallIntegerField(null=True, db_column=b'CEFSPRYPNT')),
                ('ceftrusted', models.SmallIntegerField(null=True, db_column=b'CEFTRUSTED')),
                ('dpaltcom', models.SmallIntegerField(null=True, db_column=b'DPALTCOM')),
                ('dpbnread', models.SmallIntegerField(null=True, db_column=b'DPBNREAD')),
                ('dpdrfood', models.SmallIntegerField(null=True, db_column=b'DPDRFOOD')),
                ('dpemwater', models.SmallIntegerField(null=True, db_column=b'DPEMWATER')),
                ('dpevacpets', models.SmallIntegerField(null=True, db_column=b'DPEVACPETS')),
                ('dpevfin', models.SmallIntegerField(null=True, db_column=b'DPEVFIN')),
                ('dpevinfo', models.SmallIntegerField(null=True, db_column=b'DPEVINFO')),
                ('dpevkit', models.SmallIntegerField(null=True, db_column=b'DPEVKIT')),
                ('dpevloc', models.SmallIntegerField(null=True, db_column=b'DPEVLOC')),
                ('dpevsep', models.SmallIntegerField(null=True, db_column=b'DPEVSEP')),
                ('dpevvehic', models.SmallIntegerField(null=True, db_column=b'DPEVVEHIC')),
                ('dpgenert', models.SmallIntegerField(null=True, db_column=b'DPGENERT')),
                ('drugstore', models.SmallIntegerField(null=True, db_column=b'DRUGSTORE')),
                ('eaban', models.SmallIntegerField(null=True, db_column=b'EABAN')),
                ('eage', models.SmallIntegerField(null=True, db_column=b'EAGE')),
                ('ebarcl', models.SmallIntegerField(null=True, db_column=b'EBARCL')),
                ('ecom1', models.SmallIntegerField(null=True, db_column=b'ECOM1')),
                ('ecom2', models.SmallIntegerField(null=True, db_column=b'ECOM2')),
                ('egreen', models.SmallIntegerField(null=True, db_column=b'EGREEN')),
                ('eheight', models.SmallIntegerField(null=True, db_column=b'EHEIGHT')),
                ('ejunk', models.SmallIntegerField(null=True, db_column=b'EJUNK')),
                ('eprkg', models.SmallIntegerField(null=True, db_column=b'EPRKG')),
                ('eroad', models.SmallIntegerField(null=True, db_column=b'EROAD')),
                ('etrans', models.SmallIntegerField(null=True, db_column=b'ETRANS')),
                ('ewater', models.SmallIntegerField(null=True, db_column=b'EWATER')),
                ('friends', models.SmallIntegerField(null=True, db_column=b'FRIENDS')),
                ('grocery', models.SmallIntegerField(null=True, db_column=b'GROCERY')),
                ('nhdbldmh', models.SmallIntegerField(null=True, db_column=b'NHDBLDMH')),
                ('nhdbldmu', models.SmallIntegerField(null=True, db_column=b'NHDBLDMU')),
                ('nhdbldsua', models.SmallIntegerField(null=True, db_column=b'NHDBLDSUA')),
                ('nhdbldsud', models.SmallIntegerField(null=True, db_column=b'NHDBLDSUD')),
                ('ptbank', models.SmallIntegerField(null=True, db_column=b'PTBANK')),
                ('ptcostcarm', models.IntegerField(null=True, db_column=b'PTCOSTCARM')),
                ('ptcostcarp', models.IntegerField(null=True, db_column=b'PTCOSTCARP')),
                ('ptcostgas', models.IntegerField(null=True, db_column=b'PTCOSTGAS')),
                ('ptcostinsu', models.IntegerField(null=True, db_column=b'PTCOSTINSU')),
                ('ptcostpark', models.IntegerField(null=True, db_column=b'PTCOSTPARK')),
                ('ptcostptr', models.IntegerField(null=True, db_column=b'PTCOSTPTR')),
                ('ptdisbus', models.SmallIntegerField(null=True, db_column=b'PTDISBUS')),
                ('ptdispub', models.SmallIntegerField(null=True, db_column=b'PTDISPUB')),
                ('ptdisrail', models.SmallIntegerField(null=True, db_column=b'PTDISRAIL')),
                ('ptdisshut', models.SmallIntegerField(null=True, db_column=b'PTDISSHUT')),
                ('ptdissub', models.SmallIntegerField(null=True, db_column=b'PTDISSUB')),
                ('ptentmnt', models.SmallIntegerField(null=True, db_column=b'PTENTMNT')),
                ('ptgetbus', models.SmallIntegerField(null=True, db_column=b'PTGETBUS')),
                ('ptgetrail', models.SmallIntegerField(null=True, db_column=b'PTGETRAIL')),
                ('ptgetshut', models.SmallIntegerField(null=True, db_column=b'PTGETSHUT')),
                ('ptgetsub', models.SmallIntegerField(null=True, db_column=b'PTGETSUB')),
                ('ptgrocer', models.SmallIntegerField(null=True, db_column=b'PTGROCER')),
                ('pthealth', models.SmallIntegerField(null=True, db_column=b'PTHEALTH')),
                ('ptoftbus', models.SmallIntegerField(null=True, db_column=b'PTOFTBUS')),
                ('ptoftrail', models.SmallIntegerField(null=True, db_column=b'PTOFTRAIL')),
                ('ptoftshut', models.SmallIntegerField(null=True, db_column=b'PTOFTSHUT')),
                ('ptoftsub', models.SmallIntegerField(null=True, db_column=b'PTOFTSUB')),
                ('ptpubtrn', models.SmallIntegerField(null=True, db_column=b'PTPUBTRN')),
                ('ptretail', models.SmallIntegerField(null=True, db_column=b'PTRETAIL')),
                ('ptservic', models.SmallIntegerField(null=True, db_column=b'PTSERVIC')),
                ('ptusbus', models.SmallIntegerField(null=True, db_column=b'PTUSBUS')),
                ('ptuscrpl', models.SmallIntegerField(null=True, db_column=b'PTUSCRPL')),
                ('ptuscrsh', models.SmallIntegerField(null=True, db_column=b'PTUSCRSH')),
                ('ptusotr', models.SmallIntegerField(null=True, db_column=b'PTUSOTR')),
                ('ptusrail', models.SmallIntegerField(null=True, db_column=b'PTUSRAIL')),
                ('ptusshut', models.SmallIntegerField(null=True, db_column=b'PTUSSHUT')),
                ('ptussub', models.SmallIntegerField(null=True, db_column=b'PTUSSUB')),
                ('ptustaxi', models.SmallIntegerField(null=True, db_column=b'PTUSTAXI')),
                ('ptwkschl', models.SmallIntegerField(null=True, db_column=b'PTWKSCHL')),
                ('satpol', models.SmallIntegerField(null=True, db_column=b'SATPOL')),
                ('spltwgt1', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'SPLTWGT1')),
                ('spltwgt2', models.DecimalField(null=True, decimal_places=10, max_digits=20, db_column=b'SPLTWGT2')),
                ('talknbor', models.SmallIntegerField(null=True, db_column=b'TALKNBOR')),
                ('volnteer', models.SmallIntegerField(null=True, db_column=b'VOLNTEER')),
                ('wbbank', models.SmallIntegerField(null=True, db_column=b'WBBANK')),
                ('wbbikelane', models.SmallIntegerField(null=True, db_column=b'WBBIKELANE')),
                ('wbbikewalk', models.SmallIntegerField(null=True, db_column=b'WBBIKEWALK')),
                ('wbentmnt', models.SmallIntegerField(null=True, db_column=b'WBENTMNT')),
                ('wbgrocer', models.SmallIntegerField(null=True, db_column=b'WBGROCER')),
                ('wbhealth', models.SmallIntegerField(null=True, db_column=b'WBHEALTH')),
                ('wbnobike', models.SmallIntegerField(null=True, db_column=b'WBNOBIKE')),
                ('wbnobkbdsw', models.SmallIntegerField(null=True, db_column=b'WBNOBKBDSW')),
                ('wbnobkbike', models.SmallIntegerField(null=True, db_column=b'WBNOBKBIKE')),
                ('wbnobkcrim', models.SmallIntegerField(null=True, db_column=b'WBNOBKCRIM')),
                ('wbnobkdest', models.SmallIntegerField(null=True, db_column=b'WBNOBKDEST')),
                ('wbnobkfast', models.SmallIntegerField(null=True, db_column=b'WBNOBKFAST')),
                ('wbnobkhlth', models.SmallIntegerField(null=True, db_column=b'WBNOBKHLTH')),
                ('wbnobklane', models.SmallIntegerField(null=True, db_column=b'WBNOBKLANE')),
                ('wbnobklite', models.SmallIntegerField(null=True, db_column=b'WBNOBKLITE')),
                ('wbnobknosw', models.SmallIntegerField(null=True, db_column=b'WBNOBKNOSW')),
                ('wbnobkothr', models.SmallIntegerField(null=True, db_column=b'WBNOBKOTHR')),
                ('wbnobktime', models.SmallIntegerField(null=True, db_column=b'WBNOBKTIME')),
                ('wbnobktraf', models.SmallIntegerField(null=True, db_column=b'WBNOBKTRAF')),
                ('wbretail', models.SmallIntegerField(null=True, db_column=b'WBRETAIL')),
                ('wbservic', models.SmallIntegerField(null=True, db_column=b'WBSERVIC')),
                ('wbsidewalk', models.SmallIntegerField(null=True, db_column=b'WBSIDEWALK')),
                ('wbwkschl', models.SmallIntegerField(null=True, db_column=b'WBWKSCHL')),
                ('wfprop', models.SmallIntegerField(null=True, db_column=b'WFPROP')),
                ('export_year', models.PositiveSmallIntegerField(null=True, db_index=True)),
            ],
            options={
                'db_table': 'ahs_topical',
            },
        ),
        migrations.AlterIndexTogether(
            name='topical',
            index_together=set([('control', 'export_year')]),
        ),
    ]
